const subjects={
SD:["Bahasa Indonesia","Matematika","IPAS","Pendidikan Pancasila","Pendidikan Agama","Bahasa Inggris","Seni","PJOK"],
SMP:["Bahasa Indonesia","Matematika","IPA","IPS","Bahasa Inggris","Pendidikan Pancasila","Pendidikan Agama","Informatika","Seni Budaya","PJOK"],
SMA:["Bahasa Indonesia","Matematika","Bahasa Inggris","Pendidikan Pancasila","Pendidikan Agama","Informatika","Fisika","Kimia","Biologi","Ekonomi","Sosiologi","Geografi","Sejarah"]
};
const icons={"Bahasa Indonesia":"📖","Matematika":"📐","IPAS":"🌱","IPA":"🔬","IPS":"🌍","Bahasa Inggris":"🔤","Pendidikan Pancasila":"🇮🇩","Pendidikan Agama":"🕌","Informatika":"💻","Seni":"🎨","Seni Budaya":"🎭","PJOK":"⚽","Fisika":"⚛️","Kimia":"🧪","Biologi":"🧬","Ekonomi":"💰","Sosiologi":"👥","Geografi":"🗺️","Sejarah":"🏛️"};
const mats={
"Matematika":["Bilangan dan Operasi","Pecahan","Aljabar Dasar","Geometri","Statistika"],
"Bahasa Indonesia":["Membaca dan Memahami Teks","Teks Deskripsi","Teks Narasi","Ejaan dan Kalimat","Menulis"],
"IPA":["Makhluk Hidup","Zat dan Perubahannya","Energi","Sistem Organ","Ekosistem"],
"IPAS":["Lingkungan","Makhluk Hidup","Energi","Benda di Sekitar Kita","Masyarakat"],
"IPS":["Peta dan Wilayah","Interaksi Sosial","Kegiatan Ekonomi","Sejarah Indonesia","Keragaman Budaya"],
"Informatika":["Algoritma","Sistem Komputer","Jaringan","Data","Keamanan Digital"],
"Bahasa Inggris":["Vocabulary","Simple Present","Daily Activities","Descriptive Text","Reading"],
"Pendidikan Pancasila":["Pancasila","Hak dan Kewajiban","Gotong Royong","Norma","Keberagaman"],
"Fisika":["Besaran dan Satuan","Gerak","Gaya","Energi","Gelombang"],
"Kimia":["Atom","Unsur dan Senyawa","Ikatan Kimia","Reaksi Kimia","Larutan"],
"Biologi":["Sel","Jaringan","Genetika","Ekosistem","Evolusi"],
"Ekonomi":["Kebutuhan","Pasar","Permintaan dan Penawaran","Uang","Kegiatan Ekonomi"],
"Sosiologi":["Interaksi Sosial","Nilai dan Norma","Kelompok Sosial","Perubahan Sosial","Konflik"],
"Geografi":["Peta","Atmosfer","Litosfer","Hidrosfer","Kependudukan"],
"Sejarah":["Kerajaan Nusantara","Kolonialisme","Pergerakan Nasional","Proklamasi","Indonesia Modern"]
};
const fallback=["Materi Dasar","Konsep Utama","Latihan","Penerapan","Rangkuman"];
const bank=[
["m1","SD","Matematika","Bilangan dan Operasi","Berapa hasil dari 7 + 5? ",["10","11","12","13"],"12","Penjumlahan 7 dan 5 menghasilkan 12."],
["m2","SD","Matematika","Bilangan dan Operasi","Bilangan manakah yang paling besar?",["8","6","9","7"],"9","9 lebih besar daripada 8, 6, dan 7."],
["m3","SMP","Matematika","Aljabar Dasar","Jika x = 4, berapa nilai 3x + 2?",["10","12","14","16"],"14","3 × 4 + 2 = 14."],
["m4","SMP","IPA","Energi","Sumber energi utama bagi kehidupan di Bumi adalah...",["Bulan","Matahari","Angin","Batu"],"Matahari","Matahari menyediakan energi utama bagi banyak proses kehidupan."],
["m5","SMP","Informatika","Algoritma","Urutan langkah logis untuk menyelesaikan masalah disebut...",["Algoritma","Browser","Folder","Monitor"],"Algoritma","Algoritma adalah langkah-langkah terurut untuk menyelesaikan masalah."],
["m6","SMA","Fisika","Gerak","Satuan SI untuk kecepatan adalah...",["kg","m/s","N","J"],"m/s","Kecepatan memiliki satuan meter per sekon."],
["m7","SMA","Biologi","Sel","Organel yang dikenal sebagai tempat utama respirasi sel adalah...",["Ribosom","Mitokondria","Nukleus","Vakuola"],"Mitokondria","Mitokondria menghasilkan sebagian besar energi sel melalui respirasi."],
["m8","SMA","Kimia","Atom","Partikel bermuatan negatif dalam atom adalah...",["Proton","Neutron","Elektron","Nukleon"],"Elektron","Elektron bermuatan listrik negatif."]
];
const essays=[
["e1","Matematika","Jelaskan dengan contoh sederhana apa yang dimaksud pecahan.","Pecahan menyatakan bagian dari keseluruhan dan dapat ditulis sebagai pembilang dibagi penyebut.","pecahan"],
["e2","Bahasa Indonesia","Apa yang dimaksud dengan teks deskripsi? Jelaskan cirinya.","Teks deskripsi menggambarkan objek secara jelas dan terperinci sehingga pembaca dapat membayangkannya.","deskripsi"],
["e3","Informatika","Jelaskan apa yang dimaksud algoritma.","Algoritma adalah langkah-langkah logis dan terurut untuk menyelesaikan suatu masalah.","algoritma"],
["e4","IPA","Jelaskan mengapa tumbuhan penting bagi ekosistem.","Tumbuhan berperan sebagai produsen dan membantu menyediakan makanan serta oksigen dalam ekosistem.","tumbuhan"]
];
let state=JSON.parse(localStorage.getItem("avState")||"null")||{user:null,progress:{},history:[]};
const $=id=>document.getElementById(id);
function save(){localStorage.setItem("avState",JSON.stringify(state))}
function toast(t){$("toast").textContent=t;$("toast").classList.add("show");setTimeout(()=>$("toast").classList.remove("show"),2200)}
function classes(level){let a=level==="SD"?[1,2,3,4,5,6]:level==="SMP"?[7,8,9]:[10,11,12];return a}
function updateClass(){let l=$("levelInput").value;$("classInput").innerHTML='<option value="">Pilih kelas</option>'+classes(l).map(x=>`<option value="${x}">Kelas ${x}</option>`).join("")}
$("levelInput").onchange=updateClass;
$("loginBtn").onclick=()=>{let n=$("nameInput").value.trim(),l=$("levelInput").value,c=$("classInput").value;if(!n||!l||!c)return toast("Lengkapi nama, jenjang, dan kelas dulu.");state.user={name:n,level:l,class:c};save();showApp();render("dashboard")};
$("logoutBtn").onclick=()=>{state.user=null;save();$("appPage").classList.add("hidden");$("loginPage").classList.remove("hidden")}
function showApp(){$("loginPage").classList.add("hidden");$("appPage").classList.remove("hidden");$("userBadge").textContent=`${state.user.name} • Kelas ${state.user.class}`;document.querySelectorAll(".nav").forEach(x=>x.onclick=()=>{document.querySelectorAll(".nav").forEach(n=>n.classList.remove("active"));x.classList.add("active");$("sidebar").style.display="";render(x.dataset.view)})}
$("hamb").onclick=()=>{let s=$("sidebar");s.style.display=s.style.display==="block"?"":"block"}
function render(view){let c=$("content"); if(view==="dashboard")return dashboard(c);if(view==="subjects")return subjectsView(c);if(view==="progress")return progressView(c);if(view==="profile")return profileView(c);if(view==="quizHistory")return historyView(c,"quiz");if(view==="essayHistory")return historyView(c,"essay")}
function dashboard(c){let done=Object.keys(state.progress).length,total=5*subjects[state.user.level].length,p=Math.min(100,Math.round(done/Math.max(1,total)*100));c.innerHTML=`<div class="hero"><span class="badge">AV LEARNING</span><h1>Halo, ${state.user.name}! 👋</h1><p class="muted">Kelas ${state.user.class} ${state.user.level}. Lanjut belajar tanpa bikin otak ikut buffering.</p><div class="progressbar"><i style="width:${p}%"></i></div><small>${p}% progress materi</small></div><div class="stats"><div class="stat">📚<b>${done}</b><span class="muted">Materi dipelajari</span></div><div class="stat">📝<b>${state.history.filter(x=>x.type==="quiz").length}</b><span class="muted">Kuis dikerjakan</span></div><div class="stat">✍️<b>${state.history.filter(x=>x.type==="essay").length}</b><span class="muted">Essay dikerjakan</span></div></div><div class="section-title"><h2>Mulai belajar</h2></div><div class="grid four">${subjects[state.user.level].slice(0,4).map(s=>subjectCard(s)).join("")}</div>`}
function subjectCard(s){return `<div class="card subject-card" onclick="openSubject('${s}')"><div class="subject-icon">${icons[s]||"📘"}</div><h3>${s}</h3><p class="muted">Materi untuk kelas ${state.user.class}</p><button class="primary">Lihat Materi</button></div>`}
function subjectsView(c){c.innerHTML=`<div class="hero"><h1>📚 Materi Belajar</h1><p class="muted">Pilih mata pelajaran untuk melihat materi kelas ${state.user.class}.</p></div><input class="search" id="search" placeholder="Cari mata pelajaran atau materi..." style="width:100%;margin-bottom:15px"><div class="grid" id="subjectGrid">${subjects[state.user.level].map(subjectCard).join("")}</div>`;$("search").oninput=e=>{let q=e.target.value.toLowerCase();document.querySelectorAll("#subjectGrid .card").forEach(x=>x.style.display=x.textContent.toLowerCase().includes(q)?"":"none")}}
function openSubject(s){let list=mats[s]||fallback;$("content").innerHTML=`<div class="hero"><span class="badge">KELAS ${state.user.class} • ${s}</span><h1>${icons[s]||"📘"} ${s}</h1><p class="muted">Pilih materi yang ingin dipelajari.</p></div><div class="grid">${list.map((m,i)=>`<div class="card material"><div><span class="badge">${i<2?"Mudah":i<4?"Sedang":"Menengah"}</span><h3>${m}</h3><p class="muted">⏱️ ${8+i*3} menit • Materi + kuis + essay</p></div><button class="primary" onclick="openMaterial('${s}','${m.replaceAll("'","\\'")}')">Mulai Belajar</button></div>`).join("")}</div>`}
function openMaterial(s,m){let key=`${state.user.level}-${state.user.class}-${s}-${m}`;state.progress[key]=Math.min(100,(state.progress[key]||0)+20);save();let q=pickQuestions(s,m,5);let e=pickEssay(s);$("content").innerHTML=`<div class="hero"><span class="badge">${s}</span><h1>${m}</h1><p class="muted">Materi disusun sesuai jenjang. Baca ringkasan, lalu latihan untuk menguji pemahaman.</p></div><div class="card"><h2>📖 Materi inti</h2><p><b>${m}</b> adalah bagian penting dalam pelajaran ${s}. Pelajari konsep utamanya, perhatikan contoh, lalu coba terapkan pada soal yang berbeda.</p><h3>Contoh penerapan</h3><p>Gunakan konsep ini saat menghadapi masalah sehari-hari atau soal latihan. Fokus pada langkah penyelesaian, bukan sekadar menghafal.</p><h3>Ringkasan</h3><ul><li>Pahami istilah dan konsep utama.</li><li>Perhatikan hubungan sebab-akibat atau langkah penyelesaian.</li><li>Latih dengan soal yang bervariasi.</li></ul><div class="quiz-actions"><button class="primary" onclick='startQuiz(${JSON.stringify(q)},"${s}","${m}")'>📝 Mulai Kuis</button><button class="ghost" onclick='startEssay(${JSON.stringify(e)},"${s}","${m}")'>✍️ Latihan Essay</button></div></div>`}
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function pickQuestions(s,m,n){let pool=bank.filter(x=>x[2]===s);if(!pool.length)pool=bank.filter(x=>x[1]===state.user.level);return shuffle(pool).slice(0,Math.min(n,pool.length))}
function pickEssay(s){let p=essays.filter(x=>x[1]===s);return shuffle(p.length?p:essays)[0]}
let quizSession=null;
function startQuiz(qs,s,m){quizSession={qs:qs.map(q=>({...q,opts:shuffle(q[5])})),i:0,answers:[],s,m};drawQuiz()}
function drawQuiz(){let q=quizSession.qs[quizSession.i],n=quizSession.qs.length,sel=quizSession.answers[quizSession.i];$("content").innerHTML=`<div class="quizbox"><span class="badge">SOAL ${quizSession.i+1} / ${n}</span><div class="progressbar" style="margin:12px 0 22px"><i style="width:${(quizSession.i/n)*100}%"></i></div><h2>${q[4]}</h2><div>${q[5].map(o=>`<button class="option ${sel===o?"selected":""}" onclick="quizSelect(this,${JSON.stringify(o)})">${o}</button>`).join("")}</div><div class="quiz-actions">${quizSession.i?'<button class="ghost" onclick="quizBack()">← Kembali</button>':'<span></span>'}<button class="primary" onclick="quizNext()">${quizSession.i===n-1?"Selesai":"Berikutnya →"}</button></div></div>`}
function quizSelect(_,v){quizSession.answers[quizSession.i]=v;drawQuiz()}
function quizBack(){quizSession.i--;drawQuiz()}
function quizNext(){if(!quizSession.answers[quizSession.i])return toast("Pilih jawaban dulu.");if(quizSession.i<quizSession.qs.length-1){quizSession.i++;drawQuiz()}else finishQuiz()}
function finishQuiz(){let score=0;quizSession.qs.forEach((q,i)=>{if(quizSession.answers[i]===q[6])score++});let pct=Math.round(score/quizSession.qs.length*100);state.history.unshift({type:"quiz",date:new Date().toLocaleString("id-ID"),subject:quizSession.s,material:quizSession.m,score:pct});save();$("content").innerHTML=`<div class="quizbox result"><div class="score">${pct}</div><h1>Kuis selesai 🎉</h1><p>${score} dari ${quizSession.qs.length} jawaban benar.</p><button class="primary" onclick="render('subjects')">Kembali ke Materi</button></div>`}
function startEssay(e,s,m){$("content").innerHTML=`<div class="quizbox"><span class="badge">ESSAY • ${s}</span><h2>${e[2]}</h2><textarea class="textarea" id="essayAnswer" placeholder="Tulis jawaban kamu di sini..."></textarea><div class="quiz-actions"><button class="ghost" onclick="render('subjects')">Batal</button><button class="primary" onclick='finishEssay(${JSON.stringify(e)},"${s}","${m}")'>Kirim Jawaban</button></div></div>`}
function finishEssay(e,s,m){let a=$("essayAnswer").value.trim(),keys=e[4].split(",").filter(Boolean),hits=keys.filter(k=>a.toLowerCase().includes(k)).length,pct=a.length<20?40:Math.min(100,60+hits*20);state.history.unshift({type:"essay",date:new Date().toLocaleString("id-ID"),subject:s,material:m,score:pct});save();$("content").innerHTML=`<div class="quizbox"><h1>Hasil Essay ✍️</h1><div class="score">${pct}</div><h3>Feedback</h3><p>${a.length<20?"Jawaban masih terlalu singkat. Tambahkan penjelasan dan contoh.":"Jawaban sudah cukup untuk latihan. Cek referensi di bawah agar pemahamanmu makin kuat."}</p><h3>Jawaban referensi</h3><p>${e[3]}</p><button class="primary" onclick="render('subjects')">Kembali</button></div>`}
function progressView(c){let vals=Object.values(state.progress),p=vals.length?Math.round(vals.reduce((a,b)=>a+b,0)/vals.length):0;c.innerHTML=`<div class="hero"><h1>📊 Progress Belajar</h1><p class="muted">Progress tersimpan otomatis di perangkat ini.</p><div class="progressbar"><i style="width:${p}%"></i></div><b>${p}% rata-rata progress</b></div><div class="grid"><div class="stat"><b>${Object.keys(state.progress).length}</b><span class="muted">Materi dimulai</span></div><div class="stat"><b>${state.history.filter(x=>x.type==="quiz").length}</b><span class="muted">Kuis</span></div><div class="stat"><b>${state.history.filter(x=>x.type==="essay").length}</b><span class="muted">Essay</span></div></div>`}
function historyView(c,type){let h=state.history.filter(x=>x.type===type);c.innerHTML=`<div class="hero"><h1>${type==="quiz"?"📝 Riwayat Kuis":"✍️ Riwayat Essay"}</h1><p class="muted">Nilai latihan kamu tersimpan di perangkat.</p></div>${h.length?`<table class="table"><tr><th>Tanggal</th><th>Pelajaran</th><th>Materi</th><th>Nilai</th></tr>${h.slice(0,30).map(x=>`<tr><td>${x.date}</td><td>${x.subject}</td><td>${x.material}</td><td><b>${x.score}</b></td></tr>`).join("")}</table>`:'<div class="card empty">Belum ada riwayat. Gas belajar dulu, jangan cuma menatap dashboard. 🗿</div>'}`}
function profileView(c){c.innerHTML=`<div class="hero"><h1>👤 Profil</h1><p class="muted">Data akun lokal perangkat ini.</p></div><div class="card"><h2>${state.user.name}</h2><p>Jenjang: <b>${state.user.level}</b></p><p>Kelas: <b>${state.user.class}</b></p><button class="primary" onclick="logoutBtn.click()">Keluar</button></div>`}
if(state.user){showApp();render("dashboard")}
